### ISSUE TITLE
syntax error with hiera

### ISSUE THREAD

**Issue by davidbernick** [pcfens/puppet-filebeat#140]
Hi!

I'm a novice with Puppet so the answer to this is probably, "my syntax is bad". I'm pretty sure this isn't a bug on your end. 

I'm getting this error:

```
Syntax error at 'String'; expected ')' at /etc/puppet/environments/logit/modules/filebeat/manifests/init.pp:47
```

Using Hiera files with puppet. Here's my hiera. I do not reference filebeat anywhere else (other than my Puppetfile). Don't know if I need to load anything special.

```
---
classes:
    - filebeat
filebeat::prospectors:
  syslogs:
    ensure: 'present'
    paths:
      - '/var/log/messages'
      - '/var/log/secure'
    ignore_older: '12h'
    input_type: 'log'
    doc_type: 'syslog'
filebeat::outputs:
  logstash:
    hosts:
      - xxxxxxxx:20000
    loadbalance: true
    ssl:
      enabled: true
    worker: 2
```
