### ISSUE TITLE
please add option use filebeat reload prospectors

### ISSUE THREAD

**Issue by lied** [pcfens/puppet-filebeat#145]
It's possible to configure Filebeat to reload it's prospector config dir with a given frequency

``` yaml
filebeat.config.prospectors:
  path: configs/*.yml
  reload.enabled: true
  reload.period: 10s
```

This needs to be in the main section of the filebeat.yml config file. More info available here https://www.elastic.co/guide/en/beats/filebeat/5.6/filebeat-configuration-reloading.html
