### ISSUE TITLE
filebeats inputs are not supported

### ISSUE THREAD

**Issue by rwaffen** [pcfens/puppet-filebeat#197]
inputs are the new prospectors, but they are not supported by this module :(

se: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html

**Comment by pcfens** [comment]
Changing the name is on the todo list (it'll be a breaking change if anyone is still using beats 5), but for now, they work the same. The prospectors stuff should keep working until version 7.

Are there any particular features in the inputs stuff that you're looking for?

**Comment by rwaffen** [comment]
had some problem with declaring a syslog prospector using udp protocol and another output server and port

```
filebeat::prospector:
  syslog:
    input_type: syslog
    protocol:
      udp:
        host: 'log.example.net:5140'
    tags:
      - syslog
```

and it is really confusing, because everybody on the net is using inputs and all the searches leading to input docu. and than, you can't configure an input...
