### ISSUE TITLE
Example of valid hieradata

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [pcfens/puppet-filebeat#203]
Hi,
I think that usage documentation should include valid example of hieradata.
After several tries it worked:
```
filebeat:fields_under_root: true
filebeat:fields:
    codec: plain
    token: abcdef
filebeat::prospectors:
  syslogs:
    input_type: log
    paths:
      - /var/log/dmesg
      - /var/log/firewalld
      - /var/log/maillog
      - /var/log/yum.log
    ignore_older: 3h
filebeat::outputs:
  logstash:
    hosts:
      - listener.myservice
    ssl:
      certificate_authorities:
        - /etc/pki/tls/certs/mycertificate.crt
```

It looks like I can't pass everything as a huge hash and has to split everything into several root fields in my hieradata.

I'm using CentOS7, Puppet Server 5.3.6 and Agent 5.5.8
