### ISSUE TITLE
modify systemd filebeat service file

### ISSUE THREAD

**Issue by freibuis** [pcfens/puppet-filebeat#222]
Currently installing filebeat 7.x onto a system with systemd the defaults interfer with `filebeat.yml` file
```
[Unit]
Description=Filebeat sends log files to Logstash or directly to Elasticsearch.
Documentation=https://www.elastic.co/products/beats/filebeat
Wants=network-online.target
After=network-online.target

[Service]

Environment="BEAT_LOG_OPTS=-e"
Environment="BEAT_CONFIG_OPTS=-c /etc/filebeat/filebeat.yml"
Environment="BEAT_PATH_OPTS=-path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat"
ExecStart=/usr/share/filebeat/bin/filebeat $BEAT_LOG_OPTS $BEAT_CONFIG_OPTS $BEAT_PATH_OPTS
Restart=always

[Install]
WantedBy=multi-user.target
```
the line 
```
Environment="BEAT_LOG_OPTS=-e"
```
with `-e` flag defaults logging to syslog and will ignore any logging configs

example:
```yaml
logging:
  level: debug
  to_syslog: false
  metrics:
    enabled: false
  to_files: true
  files:
    path: "/var/log/filebeat"
    name: filebeat
    keepfiles: '7'
    permissions: '0644'
```
so the question.
should this module control the filebeat systemd service file or should this be done externally?
