### ISSUE TITLE
Can't define input type syslog

### ISSUE THREAD

**Issue by trunet** [pcfens/puppet-filebeat#232]
It's currently not possible to have a [syslog input].

hiera file:
```
filebeat::inputs:
  syslog-tcp:
    input_type: syslog
    protocol:
      tcp:
        host: '0.0.0.0:514'
    tags:
      - syslog
```

error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Filebeat::Input[syslog-tcp]: has no parameter named 'protocol' (file: /etc/puppetlabs/code/environments/addElasticsearch/modules/filebeat/manifests/init.pp, line: 147) on node [REDACTED]
```

[syslog input]: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-syslog.html
