### ISSUE TITLE
Having an empty  monitoring section in filebeat.yml generates startup errors for filebeat 7.x

### ISSUE THREAD

**Issue by tullis** [pcfens/puppet-filebeat#257]
Thanks for your work on this module.

I created a filebeat using a basic logstash output with a single host.
My generated `/etc/filebeat/filebeat.yml` is included below:

When puppet tries to start the service there is an error logged:

`Exiting: No monitoring reporter configured`

If I remove the following line from the configuration, it starts up successfully:

`monitoring: {}`

I am not using xpack monitoring, so I thought that the defaults should work.
I can see that the monitoring options were recently added in this commit: https://github.com/pcfens/puppet-filebeat/commit/5aa008eff7982d7fba27638c05e0ae43592754e1

```
### Filebeat configuration managed by Puppet ###
---
shutdown_timeout: '0'
name: myfqdn.example.com
tags: []
fields: {}
fields_under_root: false
filebeat:
  config.inputs:
    enabled: true
    path: "/etc/filebeat/conf.d/*.yml"
  config.modules:
    enabled: false
    path: "/etc/filebeat/modules.d/*.yml"
  shutdown_timeout: '0'
  modules: []
http: {}
output:
  logstash:
    hosts:
    - logstash_host:5044
shipper: {}
logging: {}
runoptions: {}
processors: []
monitoring: {}
setup: {}
```
