### ISSUE TITLE
Filestream not fully implemented

### ISSUE THREAD

**Issue by Fabian1976** [pcfens/puppet-filebeat#323]
We found out that after upgrading to the most recent filebeat puppet module our filebeat harvesters for JSON files (ndjson) didn't work anymore.

The JSON filtering when using `filestream` as an `input_type` also changed.

The work-around for us was to explicitly add `input_type: log` to the config because the default `input_type` was changed to `filestream` (which should have been a major release instead of a minor according to semver).

When the `input_type` is set to `log`, the JSON block in the filebeat config looks like this:
```
  json:
      message_key: 'log'
      keys_under_root: true
      overwrite_keys: true
```

But when `filestream` is used, the JSON block should look like this:
```
  parsers:
    - ndjson:
        message_key: 'log'
        keys_under_root: true
        overwrite_keys: true
```
(according to [these docs](https://www.elastic.co/guide/en/beats/filebeat/7.17/filebeat-input-filestream.html#_parsers))

But the old JSON block is still used when the `input_type` is set to `filestream`.

Could you please fix this?
