### ISSUE TITLE
support for protocol.unix

### ISSUE THREAD

**Issue by tomsommer** [pcfens/puppet-filebeat#345]
Would be nice with support for
```
 - type: syslog
    protocol.unix:
      path: "/var/run/filebeat.sock"
      socket_type: datagram
      group: nginx
      mode: 775
      max_connections: 500
```
