### ISSUE TITLE
error while reading prospector definition from Hiera

### ISSUE THREAD

**Issue by vld0** [pcfens/puppet-filebeat#80]
Hi,
I have an error while trying to read prospectors declared in Hiera. 
Here is my error:
> Failure/Error: create_resources('filebeat::prospector', $prospectors_final)
> 
> Puppet::PreformattedError:
>   Evaluation Error: Error while evaluating a Function Call, no implicit conversion of String into Hash at /root/git/my_filebeat/spec/fixtures/modules/filebeat/manifests/init.pp:142:5

My Hiera definition:
```ruby
filebeat::prospectors:
  ensure: 'present'
  paths:
    - '/tmp/log/production.abc.log'
    - '/tmp/log/production.xyz.log'
  doc_type: 'log4j'
  multiline:
    pattern: '^[.*'
    negate: 'true'
    match: 'after'
```
My puppet code:
```ruby
class { 'filebeat':    
      prospectors_merge => true, #reads prospectors from hiera
    }
```
I guess the error is in my Hiera yml definition.
How to define multiple prospectors?
Thanks.

**Comment by pcfens** [comment]
Passing prospectors in using hiera calls the [create_resources](https://docs.puppet.com/puppet/latest/function.html#createresources) function. Try adding a name like like:
```yaml
filebeat::prospectors:
  production-app:
    ensure: 'present'
    paths:
      - '/tmp/log/production.urt.log'
      - '/tmp/log/production.uns.log'
    doc_type: 'log4j'
    multiline:
      pattern: '^[.*'
      negate: 'true'
      match: 'after'
```

Unless you're setting prospector defaults using hiera (some folks like to set default/common elements further down, like in common.yaml), you can omit the `prospectors_merge` parameter and use the default value (false).
